"use client";
import {useState} from "react";

const api=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8000/api/v1";
function bytesToB64(bytes:ArrayBuffer){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
function b64ToBytes(value:string){const padded=value.replaceAll("-","+").replaceAll("_","/")+"=".repeat((4-value.length%4)%4);return Uint8Array.from(atob(padded),c=>c.charCodeAt(0));}
async function savePrivateKey(key:CryptoKey){return new Promise<void>((resolve,reject)=>{const open=indexedDB.open("faztrack-device",1);open.onupgradeneeded=()=>open.result.createObjectStore("keys");open.onerror=()=>reject(open.error);open.onsuccess=()=>{const tx=open.result.transaction("keys","readwrite");tx.objectStore("keys").put(key,"active-private-key");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);};});}

export default function Enroll(){
 const [tenantCode,setTenantCode]=useState("LUMIN-PILOT");const [workerCode,setWorkerCode]=useState("EMP-001");const [pin,setPin]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function activate(){setBusy(true);setMessage("");try{
  const login=await fetch(`${api}/worker/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenant_code:tenantCode,worker_code:workerCode,pin})});const loginBody=await login.json();if(!login.ok)throw new Error("ID pekerja atau PIN tidak sesuai");const token=loginBody.data.access_token;
  const challengeResponse=await fetch(`${api}/worker/device-enrollment/challenge`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});const challengeBody=await challengeResponse.json();if(!challengeResponse.ok)throw new Error("Gagal meminta kode aktivasi");
  const generated=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);const privateJwk=await crypto.subtle.exportKey("jwk",generated.privateKey);const privateKey=await crypto.subtle.importKey("jwk",privateJwk,{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);privateJwk.d=undefined;await savePrivateKey(privateKey);
  const publicJwk=await crypto.subtle.exportKey("jwk",generated.publicKey);const challenge=challengeBody.data.challenge;const signature=await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},privateKey,b64ToBytes(challenge));
  const request=await fetch(`${api}/worker/device-enrollment/requests`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,"X-Device-Challenge":challenge},body:JSON.stringify({challenge_id:challengeBody.data.challenge_id,public_key_jwk:publicJwk,signature:bytesToB64(signature),device_label:navigator.userAgent.slice(0,120)})});const body=await request.json();if(!request.ok)throw new Error(body.detail?.message??"Aktivasi gagal");setMessage("Permintaan berhasil. Tunggu persetujuan supervisor sebelum perangkat digunakan untuk absensi.");
 }catch(error){setMessage(error instanceof Error?error.message:"Aktivasi gagal");}finally{setBusy(false);}}
 return <main className="workerPage"><section className="workerCard"><p className="eyebrow">Faztrack Attendance</p><h1>Daftarkan perangkat</h1><p>Proses ini dilakukan satu kali pada HP yang akan digunakan Ahmad atau pekerja bersangkutan.</p><label className="field"><span>Kode perusahaan</span><input value={tenantCode} onChange={e=>setTenantCode(e.target.value)}/></label><label className="field"><span>ID pekerja</span><input value={workerCode} onChange={e=>setWorkerCode(e.target.value)}/></label><label className="field"><span>PIN</span><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)}/></label><button onClick={activate} disabled={busy||!pin}>{busy?"Memproses…":"Daftarkan HP ini"}</button>{message&&<p className="noticeBox">{message}</p>}<small>Faztrack tidak membaca IMEI. Sistem membuat kunci perangkat otomatis dan mengirimkan public key saja.</small></section></main>;
}
