"use client";
import {useState} from "react";
type Preview={batch_id:string;status:"PREVIEW"|"REJECTED";counts:Record<string,number>;errors:{tab:string;row:number;error:string}[]};
export default function Home(){
 const [url,setUrl]=useState("");const [preview,setPreview]=useState<Preview|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const api=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8000/api/v1";
 function headers(){return {"Content-Type":"application/json","Authorization":`Bearer ${localStorage.getItem("faztrack_token")??""}`,"X-Tenant-ID":localStorage.getItem("faztrack_tenant_id")??""};}
 async function runPreview(){setBusy(true);setMessage("");try{const response=await fetch(`${api}/master-data/imports/google-sheets/preview`,{method:"POST",headers:headers(),body:JSON.stringify({spreadsheet_url:url})});const body=await response.json();if(!response.ok)throw new Error(response.status===401?"Silakan masuk sebagai admin terlebih dahulu.":body.detail?.message??"Preview gagal");setPreview(body.data);}catch(error){setMessage(error instanceof Error?error.message:"Preview gagal");}finally{setBusy(false);}}
 async function confirm(){if(!preview)return;setBusy(true);try{const response=await fetch(`${api}/master-data/imports/${preview.batch_id}/confirm`,{method:"POST",headers:headers()});const body=await response.json();if(!response.ok)throw new Error(body.detail?.code??"Konfirmasi gagal");setMessage("Master data berhasil diterapkan tanpa duplikasi.");}catch(error){setMessage(error instanceof Error?error.message:"Konfirmasi gagal");}finally{setBusy(false);}}
 return <main className="shell"><aside><div className="brand">Faztrack <span>Attendance</span></div><nav><a className="active" href="/">Master Data</a><a href="/devices">Persetujuan HP</a><a href="/review">Review GPS</a><a href="/timesheets">Rekap Kehadiran</a><a href="/attendance">Absensi Pekerja</a></nav><a className="loginLink" href="/login">Masuk admin / supervisor</a><small>Workspace perusahaan aktif</small></aside><section className="workspace"><header><div><p className="eyebrow">M1 · Admin workspace</p><h1>Master data lapangan</h1><p>Kelola proyek, pekerja, penempatan, jadwal, dan supervisor melalui satu Google Sheet.</p></div><span className="phase">Preview → Validasi → Konfirmasi</span></header><article className="panel gettingStarted"><h2>Cara mulai</h2><ol><li>Masuk sebagai admin, lalu tempel link Google Sheet dengan 5 tab wajib.</li><li>Klik <b>Preview data</b>, periksa hasilnya, lalu konfirmasi.</li><li>Pekerja membuka <a href="/enroll">Daftarkan HP</a>.</li><li>Supervisor menyetujuinya di <a href="/devices">Persetujuan HP</a>.</li><li>Pekerja membuka <a href="/attendance">Absensi Pekerja</a> untuk check-in dan check-out.</li></ol></article><div className="metrics"><article><span>Target pekerja pilot</span><strong>50</strong></article><article><span>Estimasi proyek</span><strong>7</strong></article><article><span>Jam kerja default</span><strong>08–17</strong></article><article><span>Sumber master</span><strong>Sheets</strong></article></div><article className="panel"><div className="panelHead"><div><h2>Impor Google Sheets</h2><p>Sheet harus dapat dibaca melalui link. Data belum tersimpan ketika preview.</p></div><span className="status">5 tab wajib</span></div><label className="field"><span>Link Google Sheets</span><div className="inputRow"><input value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://docs.google.com/spreadsheets/d/.../edit"/><button onClick={runPreview} disabled={busy||!url}>{busy?"Memproses…":"Preview data"}</button></div></label>{!url&&<p className="fieldHint">Tombol Preview aktif setelah link Google Sheets ditempel.</p>}<div className="tabs">{["Projects","Workers","Assignments","Schedules","Supervisors"].map(tab=><span key={tab}>{tab}</span>)}</div>{preview&&<section className="preview"><div className="panelHead"><div><h2>{preview.status==="PREVIEW"?"Siap dikonfirmasi":"Perlu diperbaiki"}</h2><p>{Object.entries(preview.counts).map(([tab,count])=>`${tab}: ${count}`).join(" · ")}</p></div>{preview.status==="PREVIEW"&&<button onClick={confirm} disabled={busy}>Konfirmasi & terapkan</button>}</div>{preview.errors.map((error,index)=><p className="error" key={index}>{error.tab} baris {error.row}: {error.error}</p>)}</section>}{message&&<p className="notice">{message}</p>}</article><p className="footnote">Kode proyek dan pekerja adalah identitas tetap. Nama, lokasi, radius, jadwal, dan penempatan dapat diperbarui melalui impor berikutnya.</p></section></main>;
}
