"""metro_mining_m0_models

Revision ID: 7d30eba67c93
Revises: 0005_m4_timesheet_quantification
Create Date: 2026-08-21 14:43:18.143057
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7d30eba67c93'
down_revision: Union[str, None] = '0005_m4_timesheet_quantification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_entity_time', 'audit_events', ['tenant_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_table('attendance_policies',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('late_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('competency_code', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_type', sa.String(length=80), nullable=False),
    sa.Column('certification_no', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRED', 'SUSPENDED', name='competencystatus'), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_id', 'equipment_type', name='uq_competency_emp_type')
    )
    op.create_index(op.f('ix_competencies_employee_id'), 'competencies', ['employee_id'], unique=False)
    op.create_index(op.f('ix_competencies_tenant_id'), 'competencies', ['tenant_id'], unique=False)
    op.create_table('crews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('crew_code', sa.String(length=50), nullable=False),
    sa.Column('crew_name', sa.String(length=200), nullable=False),
    sa.Column('onsite_cycle_anchor', sa.Date(), nullable=True),
    sa.Column('cycle_offset_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'crew_code', name='uq_crew_tenant_code')
    )
    op.create_index(op.f('ix_crews_tenant_id'), 'crews', ['tenant_id'], unique=False)
    op.create_table('equipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('equipment_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'OUT_OF_SERVICE', name='equipmentstatus'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'equipment_code', name='uq_equipment_tenant_code')
    )
    op.create_index(op.f('ix_equipments_tenant_id'), 'equipments', ['tenant_id'], unique=False)
    op.create_table('exception_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('operating_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('rule_code', sa.String(length=80), nullable=False),
    sa.Column('rule_version', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='exceptionseverity'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'WAIVED', name='exceptionstatus'), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_events_employee_id'), 'exception_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_exception_events_rule_code'), 'exception_events', ['rule_code'], unique=False)
    op.create_index(op.f('ix_exception_events_tenant_id'), 'exception_events', ['tenant_id'], unique=False)
    op.create_index('ix_exception_tenant_date', 'exception_events', ['tenant_id', 'operating_date'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('PREVIEW', 'CONFIRMED', 'REJECTED', name='importstatus'), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'SUPERVISOR', 'WORKER', 'AUDITOR', name='rolecode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='membershipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'role', name='uq_membership_role')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=False),
    sa.Column('work_end', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_project_tenant_code')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=200), nullable=False),
    sa.Column('equipment_type_required', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'role_code', name='uq_role_tenant_code')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('roster_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('policy_key', sa.String(length=100), nullable=False),
    sa.Column('policy_value', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('confirmation_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'policy_key', name='uq_roster_policy_key')
    )
    op.create_index(op.f('ix_roster_policies_tenant_id'), 'roster_policies', ['tenant_id'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('config_snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'version_label', name='uq_rule_version_label')
    )
    op.create_index(op.f('ix_rule_versions_tenant_id'), 'rule_versions', ['tenant_id'], unique=False)
    op.create_table('shift_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('shift_code', sa.String(length=50), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=False),
    sa.Column('break_end', sa.Time(), nullable=False),
    sa.Column('handover_start', sa.Time(), nullable=False),
    sa.Column('handover_end', sa.Time(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'shift_code', name='uq_shift_tenant_code')
    )
    op.create_index(op.f('ix_shift_templates_tenant_id'), 'shift_templates', ['tenant_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('site_type', sa.Enum('MINE_SITE', 'MESS', 'BRIEFING_POINT', 'OPERATING_AREA', name='sitetype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='sitestatus'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'site_code', name='uq_site_tenant_code')
    )
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('pin_hash', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_worker_tenant_code')
    )
    op.create_index(op.f('ix_workers_tenant_id'), 'workers', ['tenant_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'worker_id', 'work_date', name='uq_worker_assignment_date')
    )
    op.create_index(op.f('ix_assignments_project_id'), 'assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_assignments_tenant_id'), 'assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assignments_work_date'), 'assignments', ['work_date'], unique=False)
    op.create_index(op.f('ix_assignments_worker_id'), 'assignments', ['worker_id'], unique=False)
    op.create_table('attendance_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('CHECK_IN', 'CHECK_OUT', name='attendancetype'), nullable=False),
    sa.Column('challenge_hash', sa.String(length=64), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_challenges_expires_at'), 'attendance_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_attendance_challenges_project_id'), 'attendance_challenges', ['project_id'], unique=False)
    op.create_index(op.f('ix_attendance_challenges_tenant_id'), 'attendance_challenges', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_challenges_work_date'), 'attendance_challenges', ['work_date'], unique=False)
    op.create_index(op.f('ix_attendance_challenges_worker_id'), 'attendance_challenges', ['worker_id'], unique=False)
    op.create_table('checkpoint_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=80), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('window_start_offset_min', sa.Integer(), nullable=False),
    sa.Column('window_end_offset_min', sa.Integer(), nullable=False),
    sa.Column('required_evidence', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'checkpoint_type', 'shift_id', name='uq_checkpoint_shift')
    )
    op.create_index(op.f('ix_checkpoint_policies_shift_id'), 'checkpoint_policies', ['shift_id'], unique=False)
    op.create_index(op.f('ix_checkpoint_policies_tenant_id'), 'checkpoint_policies', ['tenant_id'], unique=False)
    op.create_table('device_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_challenges_expires_at'), 'device_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_device_challenges_tenant_id'), 'device_challenges', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_challenges_worker_id'), 'device_challenges', ['worker_id'], unique=False)
    op.create_table('device_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('public_key_jwk', sa.Text(), nullable=False),
    sa.Column('public_key_thumbprint', sa.String(length=64), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='enrollmentstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_enrollments_public_key_thumbprint'), 'device_enrollments', ['public_key_thumbprint'], unique=False)
    op.create_index(op.f('ix_device_enrollments_status'), 'device_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_device_enrollments_tenant_id'), 'device_enrollments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_enrollments_worker_id'), 'device_enrollments', ['worker_id'], unique=False)
    op.create_table('employee_meta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('crew_id', sa.String(length=36), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('cycle_offset_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'worker_id', name='uq_employee_meta_worker'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index(op.f('ix_employee_meta_tenant_id'), 'employee_meta', ['tenant_id'], unique=False)
    op.create_table('override_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exception_events.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_override_events_exception_id'), 'override_events', ['exception_id'], unique=False)
    op.create_index(op.f('ix_override_events_tenant_id'), 'override_events', ['tenant_id'], unique=False)
    op.create_table('project_scopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'membership_id', 'project_id', name='uq_project_scope')
    )
    op.create_index(op.f('ix_project_scopes_membership_id'), 'project_scopes', ['membership_id'], unique=False)
    op.create_index(op.f('ix_project_scopes_project_id'), 'project_scopes', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_scopes_tenant_id'), 'project_scopes', ['tenant_id'], unique=False)
    op.create_table('roster_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('roster_code', sa.String(length=50), nullable=False),
    sa.Column('operating_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('crew_id', sa.String(length=36), nullable=True),
    sa.Column('site_cycle_day', sa.Integer(), nullable=True),
    sa.Column('site_status', sa.Enum('ONSITE', 'OFFSITE', name='sitestatusenum'), nullable=False),
    sa.Column('work_status', sa.Enum('WORK', 'REST', 'OFFSITE', 'LEAVE', 'SICK', 'TRAINING', 'STANDBY', name='workstatus'), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('planned_equipment_id', sa.String(length=36), nullable=True),
    sa.Column('effective_rule_version', sa.String(length=100), nullable=True),
    sa.Column('validation_status', sa.Enum('DRAFT', 'VALID', 'INVALID', 'PUBLISHED', 'LOCKED', 'REVISED', name='validationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planned_equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_templates.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'operating_date', 'employee_id', name='uq_roster_emp_date')
    )
    op.create_index(op.f('ix_roster_assignments_employee_id'), 'roster_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_roster_assignments_tenant_id'), 'roster_assignments', ['tenant_id'], unique=False)
    op.create_index('ix_roster_tenant_crew', 'roster_assignments', ['tenant_id', 'crew_id'], unique=False)
    op.create_index('ix_roster_tenant_date', 'roster_assignments', ['tenant_id', 'operating_date'], unique=False)
    op.create_table('supervisor_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'membership_id', 'project_id', name='uq_supervisor_project')
    )
    op.create_index(op.f('ix_supervisor_projects_membership_id'), 'supervisor_projects', ['membership_id'], unique=False)
    op.create_index(op.f('ix_supervisor_projects_project_id'), 'supervisor_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_supervisor_projects_tenant_id'), 'supervisor_projects', ['tenant_id'], unique=False)
    op.create_table('timesheet_periods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('scope_key', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='timesheetperiodstatus'), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date_from', 'date_to', 'scope_key', name='uq_timesheet_period_scope')
    )
    op.create_index(op.f('ix_timesheet_periods_date_from'), 'timesheet_periods', ['date_from'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_date_to'), 'timesheet_periods', ['date_to'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_project_id'), 'timesheet_periods', ['project_id'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_status'), 'timesheet_periods', ['status'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_tenant_id'), 'timesheet_periods', ['tenant_id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'worker_id', 'work_date', name='uq_worker_schedule_date')
    )
    op.create_index(op.f('ix_work_schedules_tenant_id'), 'work_schedules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_schedules_work_date'), 'work_schedules', ['work_date'], unique=False)
    op.create_index(op.f('ix_work_schedules_worker_id'), 'work_schedules', ['worker_id'], unique=False)
    op.create_table('device_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('public_key_jwk', sa.Text(), nullable=False),
    sa.Column('public_key_thumbprint', sa.String(length=64), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='devicestatus'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('revoke_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['device_enrollments.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_device_bindings_public_key_thumbprint'), 'device_bindings', ['public_key_thumbprint'], unique=False)
    op.create_index(op.f('ix_device_bindings_status'), 'device_bindings', ['status'], unique=False)
    op.create_index(op.f('ix_device_bindings_tenant_id'), 'device_bindings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_bindings_worker_id'), 'device_bindings', ['worker_id'], unique=False)
    op.create_index('uq_active_device_per_worker', 'device_bindings', ['tenant_id', 'worker_id'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('equipment_assignments_actual',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('roster_id', sa.String(length=36), nullable=True),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['roster_assignments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_assignments_actual_employee_id'), 'equipment_assignments_actual', ['employee_id'], unique=False)
    op.create_index(op.f('ix_equipment_assignments_actual_equipment_id'), 'equipment_assignments_actual', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_assignments_actual_roster_id'), 'equipment_assignments_actual', ['roster_id'], unique=False)
    op.create_index(op.f('ix_equipment_assignments_actual_tenant_id'), 'equipment_assignments_actual', ['tenant_id'], unique=False)
    op.create_table('attendance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('device_binding_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('CHECK_IN', 'CHECK_OUT', name='attendancetype'), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVIEW', 'REJECTED', name='attendancestatus'), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('server_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at_client', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['attendance_challenges.id'], ),
    sa.ForeignKeyConstraint(['device_binding_id'], ['device_bindings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    op.create_index(op.f('ix_attendance_events_device_binding_id'), 'attendance_events', ['device_binding_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_type'), 'attendance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_attendance_events_project_id'), 'attendance_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_server_time'), 'attendance_events', ['server_time'], unique=False)
    op.create_index(op.f('ix_attendance_events_status'), 'attendance_events', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_events_tenant_id'), 'attendance_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_work_date'), 'attendance_events', ['work_date'], unique=False)
    op.create_index(op.f('ix_attendance_events_worker_id'), 'attendance_events', ['worker_id'], unique=False)
    op.create_index('uq_counted_attendance_event', 'attendance_events', ['tenant_id', 'worker_id', 'work_date', 'event_type'], unique=True, sqlite_where=sa.text("status IN ('VALID','REVIEW')"), postgresql_where=sa.text("status IN ('VALID','REVIEW')"))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_counted_attendance_event', table_name='attendance_events', sqlite_where=sa.text("status IN ('VALID','REVIEW')"), postgresql_where=sa.text("status IN ('VALID','REVIEW')"))
    op.drop_index(op.f('ix_attendance_events_worker_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_work_date'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_tenant_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_status'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_server_time'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_project_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_type'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_device_binding_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_equipment_assignments_actual_tenant_id'), table_name='equipment_assignments_actual')
    op.drop_index(op.f('ix_equipment_assignments_actual_roster_id'), table_name='equipment_assignments_actual')
    op.drop_index(op.f('ix_equipment_assignments_actual_equipment_id'), table_name='equipment_assignments_actual')
    op.drop_index(op.f('ix_equipment_assignments_actual_employee_id'), table_name='equipment_assignments_actual')
    op.drop_table('equipment_assignments_actual')
    op.drop_index('uq_active_device_per_worker', table_name='device_bindings', sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_device_bindings_worker_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_tenant_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_status'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_public_key_thumbprint'), table_name='device_bindings')
    op.drop_table('device_bindings')
    op.drop_index(op.f('ix_work_schedules_worker_id'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_work_date'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_tenant_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_timesheet_periods_tenant_id'), table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_status'), table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_project_id'), table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_date_to'), table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_date_from'), table_name='timesheet_periods')
    op.drop_table('timesheet_periods')
    op.drop_index(op.f('ix_supervisor_projects_tenant_id'), table_name='supervisor_projects')
    op.drop_index(op.f('ix_supervisor_projects_project_id'), table_name='supervisor_projects')
    op.drop_index(op.f('ix_supervisor_projects_membership_id'), table_name='supervisor_projects')
    op.drop_table('supervisor_projects')
    op.drop_index('ix_roster_tenant_date', table_name='roster_assignments')
    op.drop_index('ix_roster_tenant_crew', table_name='roster_assignments')
    op.drop_index(op.f('ix_roster_assignments_tenant_id'), table_name='roster_assignments')
    op.drop_index(op.f('ix_roster_assignments_employee_id'), table_name='roster_assignments')
    op.drop_table('roster_assignments')
    op.drop_index(op.f('ix_project_scopes_tenant_id'), table_name='project_scopes')
    op.drop_index(op.f('ix_project_scopes_project_id'), table_name='project_scopes')
    op.drop_index(op.f('ix_project_scopes_membership_id'), table_name='project_scopes')
    op.drop_table('project_scopes')
    op.drop_index(op.f('ix_override_events_tenant_id'), table_name='override_events')
    op.drop_index(op.f('ix_override_events_exception_id'), table_name='override_events')
    op.drop_table('override_events')
    op.drop_index(op.f('ix_employee_meta_tenant_id'), table_name='employee_meta')
    op.drop_table('employee_meta')
    op.drop_index(op.f('ix_device_enrollments_worker_id'), table_name='device_enrollments')
    op.drop_index(op.f('ix_device_enrollments_tenant_id'), table_name='device_enrollments')
    op.drop_index(op.f('ix_device_enrollments_status'), table_name='device_enrollments')
    op.drop_index(op.f('ix_device_enrollments_public_key_thumbprint'), table_name='device_enrollments')
    op.drop_table('device_enrollments')
    op.drop_index(op.f('ix_device_challenges_worker_id'), table_name='device_challenges')
    op.drop_index(op.f('ix_device_challenges_tenant_id'), table_name='device_challenges')
    op.drop_index(op.f('ix_device_challenges_expires_at'), table_name='device_challenges')
    op.drop_table('device_challenges')
    op.drop_index(op.f('ix_checkpoint_policies_tenant_id'), table_name='checkpoint_policies')
    op.drop_index(op.f('ix_checkpoint_policies_shift_id'), table_name='checkpoint_policies')
    op.drop_table('checkpoint_policies')
    op.drop_index(op.f('ix_attendance_challenges_worker_id'), table_name='attendance_challenges')
    op.drop_index(op.f('ix_attendance_challenges_work_date'), table_name='attendance_challenges')
    op.drop_index(op.f('ix_attendance_challenges_tenant_id'), table_name='attendance_challenges')
    op.drop_index(op.f('ix_attendance_challenges_project_id'), table_name='attendance_challenges')
    op.drop_index(op.f('ix_attendance_challenges_expires_at'), table_name='attendance_challenges')
    op.drop_table('attendance_challenges')
    op.drop_index(op.f('ix_assignments_worker_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_work_date'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_tenant_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_project_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_workers_tenant_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_shift_templates_tenant_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    op.drop_index(op.f('ix_rule_versions_tenant_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_roster_policies_tenant_id'), table_name='roster_policies')
    op.drop_table('roster_policies')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('ix_exception_tenant_date', table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_tenant_id'), table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_rule_code'), table_name='exception_events')
    op.drop_index(op.f('ix_exception_events_employee_id'), table_name='exception_events')
    op.drop_table('exception_events')
    op.drop_index(op.f('ix_equipments_tenant_id'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_crews_tenant_id'), table_name='crews')
    op.drop_table('crews')
    op.drop_index(op.f('ix_competencies_tenant_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_employee_id'), table_name='competencies')
    op.drop_table('competencies')
    op.drop_table('attendance_policies')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_audit_tenant_entity_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###

