"""m4d_hrd_import_system

Revision ID: 964bee19a3a3
Revises: d8d2bb02ba3b
Create Date: 2026-08-29 06:33:01.721910
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '964bee19a3a3'
down_revision: Union[str, None] = 'd8d2bb02ba3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='shiftrulestatus'), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('natural_language_input', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_shift_rule_tenant_name')
    )
    op.create_index(op.f('ix_shift_rules_tenant_id'), 'shift_rules', ['tenant_id'], unique=False)
    op.create_table('hrd_import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PREVIEWING', 'CONFIRMED', 'IMPORTING', 'COMPLETED', 'FAILED', name='hrdimportstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('shift_rule_id', sa.String(length=36), nullable=True),
    sa.Column('preview_json', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('mapping_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shift_rule_id'], ['shift_rules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hrd_import_batches_tenant_id'), 'hrd_import_batches', ['tenant_id'], unique=False)
    op.alter_column('attendance_events', 'site_note',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_constraint(op.f('attendance_events_challenge_id_key'), 'attendance_events', type_='unique')
    op.drop_index(op.f('uq_counted_attendance_event'), table_name='attendance_events', postgresql_where="(status = ANY (ARRAY['VALID'::attendancestatus, 'REVIEW'::attendancestatus]))")
    op.create_index('ix_counted_attendance_event', 'attendance_events', ['tenant_id', 'worker_id', 'work_date', 'event_type'], unique=False, sqlite_where=sa.text("status IN ('VALID','REVIEW')"), postgresql_where=sa.text("status IN ('VALID','REVIEW')"))
    op.alter_column('tenants', 'allow_multi_checkin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'allow_multi_checkin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_counted_attendance_event', table_name='attendance_events', sqlite_where=sa.text("status IN ('VALID','REVIEW')"), postgresql_where=sa.text("status IN ('VALID','REVIEW')"))
    op.create_index(op.f('uq_counted_attendance_event'), 'attendance_events', ['tenant_id', 'worker_id', 'work_date', 'event_type'], unique=True, postgresql_where="(status = ANY (ARRAY['VALID'::attendancestatus, 'REVIEW'::attendancestatus]))")
    op.create_unique_constraint(op.f('attendance_events_challenge_id_key'), 'attendance_events', ['challenge_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance_events', 'site_note',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_hrd_import_batches_tenant_id'), table_name='hrd_import_batches')
    op.drop_table('hrd_import_batches')
    op.drop_index(op.f('ix_shift_rules_tenant_id'), table_name='shift_rules')
    op.drop_table('shift_rules')
    # ### end Alembic commands ###

