"""m2a_canonical_attendance_event_foundation

Revision ID: af69ae8e38de
Revises: 0a9c48b007af
Create Date: 2026-08-21 17:01:41.582492
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'af69ae8e38de'
down_revision: Union[str, None] = '0a9c48b007af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_event_id', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_timestamp', sa.String(length=100), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSED', 'DUPLICATE', 'SKIPPED', 'ERROR', name='raweventstatus'), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('canonical_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'source_event_id', name='uq_raw_event_source')
    )
    op.create_index('ix_raw_event_tenant_received', 'raw_events', ['tenant_id', 'received_at'], unique=False)
    op.create_index('ix_raw_event_tenant_status', 'raw_events', ['tenant_id', 'processing_status'], unique=False)
    op.create_index(op.f('ix_raw_events_tenant_id'), 'raw_events', ['tenant_id'], unique=False)
    op.create_table('canonical_attendance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('CHECK_IN', 'CHECK_OUT', 'BREAK_IN', 'BREAK_OUT', 'BRIEFING_IN', 'BRIEFING_OUT', 'EQUIPMENT_CHECK_IN', 'EQUIPMENT_CHECK_OUT', 'HANDOVER_START', 'HANDOVER_END', 'SUPERVISOR_OVERRIDE', name='canonicaleventtype'), nullable=False),
    sa.Column('local_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utc_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('operating_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_event_id', sa.String(length=200), nullable=False),
    sa.Column('raw_event_id', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'SHIFT_RESOLVED', 'AMBIGUOUS_SHIFT', 'MISSING_SHIFT', 'VALID', 'INVALID', name='canonicalprocessingstatus'), nullable=False),
    sa.Column('roster_assignment_id', sa.String(length=36), nullable=True),
    sa.Column('legacy_attendance_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['legacy_attendance_id'], ['attendance_events.id'], ),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.ForeignKeyConstraint(['roster_assignment_id'], ['roster_assignments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_templates.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_attendance_events_employee_id'), 'canonical_attendance_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_canonical_attendance_events_tenant_id'), 'canonical_attendance_events', ['tenant_id'], unique=False)
    op.create_index('ix_canonical_raw_event', 'canonical_attendance_events', ['raw_event_id'], unique=False)
    op.create_index('ix_canonical_tenant_date', 'canonical_attendance_events', ['tenant_id', 'operating_date'], unique=False)
    op.create_index('ix_canonical_tenant_emp_date', 'canonical_attendance_events', ['tenant_id', 'employee_id', 'operating_date'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canonical_tenant_emp_date', table_name='canonical_attendance_events')
    op.drop_index('ix_canonical_tenant_date', table_name='canonical_attendance_events')
    op.drop_index('ix_canonical_raw_event', table_name='canonical_attendance_events')
    op.drop_index(op.f('ix_canonical_attendance_events_tenant_id'), table_name='canonical_attendance_events')
    op.drop_index(op.f('ix_canonical_attendance_events_employee_id'), table_name='canonical_attendance_events')
    op.drop_table('canonical_attendance_events')
    op.drop_index(op.f('ix_raw_events_tenant_id'), table_name='raw_events')
    op.drop_index('ix_raw_event_tenant_status', table_name='raw_events')
    op.drop_index('ix_raw_event_tenant_received', table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###

